[package]
name = "infinity_hal"
version = "0.1.0"
edition = "2021"
license = "MIT-0"

[lib]
name = "infinity_hal"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
