[package]
name = "ontology_integrity"
version = "0.1.0"
edition = "2021"

[dependencies]
hdi = "0.5"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "rlib"]
